### ISSUE TITLE
SLUS21628 - Hot Wheels Beat That

### ISSUE THREAD

**Issue by PistolaoBR** [shadps4-emu/shadps4-game-compatibility#1722]
### Game Name

Hot Wheels Beat That

### Game code

SLUS21628

### Game version

v01.00

### Used emulator's version (only released versions are acceptable)

v0.5.0

### Current status

Nothing

### Operating System

Windows

### Error

[Core] <Error> stubs.cpp:CommonStub:42: Stub: getpid (nid: HoLVWNanBBc) called, returning zero to 0x94fffc99e
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceKernelGetProcessType (nid: +g+UP8Pyfmo) called, returning zero to 0x94fffc9a5
[Kernel.Fs] <Info> file_system.cpp:posix_open:153: posix open redirect to sceKernelOpen
[Kernel.Fs] <Info> file_system.cpp:sceKernelOpen:61: path = /dev/deci_tty6 flags = 0x1 mode = 0
[Core.Linker] <Info> module.cpp:Start:98: Module started : libSceRtc
[Core.Linker] <Info> module.cpp:Start:98: Module started : libSceJpegEnc

### Description

Doesn't boot, stays on a black screen forever

### Screenshots

![image](https://github.com/user-attachments/assets/8728f551-7c52-4cf0-8cd5-af86e408fb77)

### Log File

[shad_log.txt](https://github.com/user-attachments/files/18278317/shad_log.txt)

**Comment by Xphalnos** [comment]
Cannot be considered valid because the files are corrupted!

`[Core.Linker] <Error> linker.cpp:LoadModule:106: Provided file D:/Roms/PS4/SLUS21628\sce_module\libc.prx is not valid ELF file`
`[Loader] <Info> emulator.cpp:Run:259: Loading D:/Roms/PS4/SLUS21628\sce_module\libSceFios2.prx`
`[Loader] <Info> elf.cpp:IsSelfFile:248: Unknown SELF file`
`[Loader] <Info> elf.cpp:IsElfFile:260: Not an ELF file magic is wrong!`
`[Loader] <Info> elf.cpp:IsElfFile:260: Not an ELF file magic is wrong!`
